# SPDX-License-Identifier: GPL-2.0+
# Libre Computer sunxi board directory
# Source files are symlinks to board/sunxi/
obj-y	+= board.o
obj-$(CONFIG_SUN7I_GMAC)	+= gmac.o
obj-$(CONFIG_MACH_SUN4I)	+= dram_sun4i_auto.o
obj-$(CONFIG_MACH_SUN5I)	+= dram_sun5i_auto.o
obj-$(CONFIG_MACH_SUN7I)	+= dram_sun5i_auto.o
obj-$(CONFIG_$(PHASE_)CHIP_DIP_SCAN)	+= chip.o
